"""setup_database

Revision ID: e74b69994f73
Revises: 
Create Date: 2026-07-12 23:21:35.113224

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e74b69994f73'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('request_responses',
    sa.Column('id_solicitud', sa.String(), nullable=False),
    sa.Column('categoria_sugerida', sa.String(), nullable=False),
    sa.Column('prioridad_sugerida', sa.String(), nullable=False),
    sa.Column('sentimiento', sa.String(), nullable=False),
    sa.Column('resumen', sa.String(), nullable=False),
    sa.Column('datos_faltantes', sa.JSON(), nullable=False),
    sa.Column('requiere_revision_humana', sa.Boolean(), nullable=False),
    sa.Column('justificacion', sa.String(), nullable=False),
    sa.Column('tokens_usados', sa.Integer(), nullable=False),
    sa.Column('modelo_usado', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    op.create_table('requests',
    sa.Column('id_solicitud', sa.String(), nullable=False),
    sa.Column('cliente', sa.String(), nullable=False),
    sa.Column('canal', sa.String(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('descripcion', sa.String(), nullable=False),
    sa.Column('producto', sa.String(), nullable=False),
    sa.Column('ciudad', sa.String(), nullable=False),
    sa.Column('prioridad_manual', sa.String(), nullable=False),
    sa.Column('comentarios_adicionales', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id_solicitud')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('requests')
    op.drop_table('request_responses')
    # ### end Alembic commands ###
